import "dotenv/config";
import OpenAI from "openai";
import { InferenceClient } from "@huggingface/inference";
import { pipeline } from "@xenova/transformers";
import { supabase } from './config.js';
import { readFile } from "node:fs/promises";
import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";

const accessToken = process.env.HF_token;
const hf = new InferenceClient(accessToken);
const apiKey = process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error(
    "Missing OPENAI_API_KEY. Put it in .env and run: npm start"
  );
  process.exit(1);
}

// const client = new OpenAI({ apiKey });


// const response = await client.responses.create({
//   model: "gpt-5-nano",
//   input: "which is best cricket team in the world?",
// });

// console.log(response.output_text);
// async function main() {
//   try {
//     const embedding = await client.embeddings.create({
//       model: "text-embedding-3-large",
//       input: "Hello, world!",
//     });
//     console.log(embedding);
//   } catch (err) {
//     const status = err?.status;
//     const code = err?.code;
//     if (status === 429 || code === "insufficient_quota") {
//       console.error(
//         "Embedding request failed due to quota/rate limit (429). Check your OpenAI plan/billing, then re-run."
//       );
//       return;
//     }
//     throw err;
//   }
// }
// main();



const embedder = await pipeline(
  "feature-extraction",
  "Xenova/all-MiniLM-L6-v2"
);

const content =  [
  "Beyond Mars (1 hr 15 min): Join space enthusiasts as they speculate about extraterrestrial life and the mysteries of distant planets.",
  "Jazz under stars (55 min): Experience a captivating night in New Orleans, where jazz melodies echo under the moonlit sky.",
  "Mysteries of the deep (1 hr 30 min): Dive with marine explorers into the uncharted caves of our oceans and uncover their hidden wonders.",
  "Rediscovering lost melodies (48 min): Journey through time to explore the resurgence of vinyl culture and its timeless appeal.",
  "Tales from the tech frontier (1 hr 5 min): Navigate the complex terrain of AI ethics, understanding its implications and challenges.",
  "The soundscape of silence (30 min): Traverse the globe with sonic explorers to find the world's most serene and silent spots.",
  "Decoding dreams (1 hr 22 min): Step into the realm of the subconscious, deciphering the intricate narratives woven by our dreams.",
  "Time capsules (50 min): Revel in the bizarre, endearing, and profound discoveries that unveil the quirks of a century past.",
  "Frozen in time (1 hr 40 min): Embark on an icy expedition, unearthing secrets hidden within the majestic ancient glaciers.",
  "Songs of the Sea (1 hr): Dive deep with marine biologists to understand the intricate whale songs echoing in our vast oceans."
];

// content.forEach(async (text) => {
//   const outputembedded = await embedder(text, {
//     pooling: "mean",
//     normalize: true,
//   });
//   console.log({ content: text, embedding: outputembedded.data });
//   await supabase.from("documents").insert({
//     content: text,
//     embedding: Array.from(outputembedded.data),
//   });
// });

const query = "Decoding orca calls";
const moviesData = await readFile(new URL("./movies.txt", import.meta.url), "utf8");
const textSplitter = new RecursiveCharacterTextSplitter({
  chunkSize: 100,
  chunkOverlap: 0,
});
const chunks = await textSplitter.createDocuments([moviesData]);
console.log(chunks);

chunks.forEach(async (singleChunk) => {
  console.log(singleChunk.pageContent);
  const outputembedded = await embedder(singleChunk.pageContent, {
    pooling: "mean",
    normalize: true,
  });
  
  // The vector generated by OpenAI
  const embedding = Array.from(outputembedded.data);
  await supabase.from("movies").insert({
    content: singleChunk.pageContent,
    embedding: embedding,
  });
})

//chunks.map((singleChunk)=> console.log(singleChunk.pageContent));
// main(query);
// async function main(input) {
//   // Create a vector embedding representing the input text
//    const outputembedded = await embedder(input, {
//     pooling: "mean",
//     normalize: true,
//   });
  
//   // The vector generated by OpenAI
//   const embedding = Array.from(outputembedded.data);
  
//   // Query Supabase for nearest vector match
//   const { data } = await supabase.rpc('match_documents', {
//     query_embedding: embedding,
//     match_threshold: 0.01, // Adjust based on your needs
//     match_count: 3
//   });
//   console.log(data);
//}
